import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#f7f7fb" },
  page: { flex: 1, paddingHorizontal: 16, paddingTop: 10 },
  tabs: { flexDirection: "row", gap: 8, marginBottom: 12 },
  tab: { paddingHorizontal: 16, paddingVertical: 9, borderRadius: 18, backgroundColor: "#e7e8ed" },
  tabActive: { backgroundColor: "#d9dcff" },
  tabText: { fontSize: 15, color: "#292a31" },
  section: { flexDirection: "row", marginBottom: 0 },
  blockRow: { flexDirection: "row", marginBottom: 0 },
  timelineList: { flexGrow: 0 },
  farSection: { marginTop: 18, borderTopWidth: 1, borderTopColor: "#d5d6de", paddingTop: 14 },
  farSectionFollow: { marginTop: 14 },
  sectionLabel: { width: 72, paddingRight: 8 },
  sectionLabelPressed: { opacity: 0.55 },
  sectionLabelSpacer: { width: 72, paddingRight: 8 },
  sectionHeaderLine: { minHeight: 20 },
  // Keep an accessible, constant-height drop target without turning a sparse
  // week into several screens of whitespace. Height must NOT change mid-drag
  // because that corrupts DraggableFlatList offsets.
  sectionHeaderLineEmpty: { minHeight: 40 },
  timelineContainer: { flex: 1 },
  primary: { fontSize: 13, fontWeight: "600", color: "#454651" },
  secondary: { fontSize: 11, color: "#858692", marginTop: 2 },
  tasksContainer: { flex: 1 },
  tasks: { borderLeftWidth: 2, borderLeftColor: "#d9dcff", paddingLeft: 10 },
  taskBlock: { width: "100%", marginBottom: 6 },
  completedCut: { flex: 1, borderTopWidth: 1, borderTopColor: "#e0e1e7", paddingVertical: 10 },
  completedCutPressed: { opacity: 0.55 },
  completedCutText: { color: "#747580", fontSize: 13 },
  task: { flexDirection: "row", alignItems: "flex-start", paddingVertical: 6, minHeight: 34 },
  child: { marginLeft: 18 },
  checkboxHitArea: { minWidth: 48, minHeight: 48, alignItems: "center", justifyContent: "center", marginRight: -14, marginTop: -7 },
  checkbox: { width: 18, height: 18, borderRadius: 9, borderWidth: 1.5, borderColor: "#858a94", alignItems: "center", justifyContent: "center" },
  checkboxDone: { backgroundColor: "#8b8f96", borderColor: "#8b8f96" },
  check: { color: "white", fontSize: 12, fontWeight: "700" },
  taskText: { flex: 1 },
  title: { fontSize: 16, color: "#25262d" },
  completed: { color: "#8b8f96", textDecorationLine: "line-through" },
  note: { color: "#747580", fontSize: 13, marginTop: 2 },
  newTask: { color: "#5559a8", fontSize: 15, paddingVertical: 12 },
  newTaskHeader: { paddingBottom: 8 },
  newTaskInputRow: { flexDirection: "row", alignItems: "stretch", gap: 8 },
  newTaskInput: { flex: 1 },
  newTaskConfirm: { minWidth: 56, marginVertical: 6, borderRadius: 9, backgroundColor: "#595ec7", alignItems: "center", justifyContent: "center", paddingHorizontal: 12 },
  newTaskConfirmText: { color: "white", fontWeight: "700" },
  sectionChips: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 8 },
  sectionChip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 16, backgroundColor: "#e7e8ed" },
  sectionChipActive: { backgroundColor: "#d9dcff" },
  sectionChipText: { fontSize: 14, color: "#292a31" },
  textarea: { flex: 1, minHeight: 300, borderWidth: 1, borderColor: "#d5d6de", borderRadius: 10, padding: 12, fontSize: 15, backgroundColor: "white" },
  button: { backgroundColor: "#595ec7", borderRadius: 9, paddingHorizontal: 14, paddingVertical: 11, marginVertical: 6 },
  buttonText: { color: "white", textAlign: "center", fontWeight: "600" },
  secondaryButton: { borderWidth: 1, borderColor: "#595ec7", borderRadius: 9, paddingHorizontal: 14, paddingVertical: 11, marginVertical: 6 },
  secondaryButtonText: { color: "#494da8", textAlign: "center", fontWeight: "600" },
  input: { borderWidth: 1, borderColor: "#d5d6de", borderRadius: 9, padding: 12, backgroundColor: "white", marginVertical: 6 },
  status: { color: "#747580", marginBottom: 8 },
  error: { color: "#a52a2a", marginVertical: 8 },
  qr: { alignSelf: "center", backgroundColor: "white", padding: 12, marginVertical: 12 },
  dragging: { backgroundColor: "white", borderRadius: 10, opacity: 0.98, elevation: 7, shadowColor: "#202135", shadowOpacity: 0.18, shadowRadius: 10, shadowOffset: { width: 0, height: 5 } },
  dragPlaceholder: { flex: 1, marginLeft: 72, marginBottom: 6, borderRadius: 8, borderWidth: 1, borderColor: "#cfd2ff", backgroundColor: "#eef0ff" },
  dropTarget: { backgroundColor: "#eef0ff", borderRadius: 8 },
  deleteButton: { minWidth: 48, minHeight: 48, alignItems: "center", justifyContent: "center", marginLeft: -8 },
  deleteButtonText: { color: "#a52a2a", fontSize: 22, lineHeight: 24, fontWeight: "600" },
  header: { flexDirection: "row", alignItems: "center", marginBottom: 12 },
  headerTabs: { flex: 1, flexDirection: "row", gap: 8 },
  menuWrap: { position: "relative" },
  menuButton: { paddingHorizontal: 10, paddingVertical: 8 },
  menuButtonText: { fontSize: 22, lineHeight: 24, color: "#454651" },
  menuPanel: { position: "absolute", top: 36, right: 0, backgroundColor: "white", borderRadius: 10, borderWidth: 1, borderColor: "#d5d6de", minWidth: 160, zIndex: 10, elevation: 4 },
  menuItem: { paddingHorizontal: 14, paddingVertical: 12 },
  menuItemText: { fontSize: 15, color: "#25262d" },
  settingsHeader: { flexDirection: "row", alignItems: "center", marginBottom: 20, gap: 12 },
  settingsBack: { paddingVertical: 4 },
  settingsBackText: { fontSize: 15, color: "#494da8" },
  settingsTitle: { fontSize: 20, fontWeight: "600", color: "#25262d" },
  settingsSectionTitle: { fontSize: 13, fontWeight: "600", color: "#454651", marginTop: 16, marginBottom: 8 },
  settingsBlock: { backgroundColor: "white", borderRadius: 10, borderWidth: 1, borderColor: "#d5d6de", padding: 12 },
  settingsActionButton: { alignSelf: "flex-start", borderWidth: 1, borderColor: "#595ec7", borderRadius: 9, paddingHorizontal: 12, paddingVertical: 8, marginVertical: 4 },
  settingsWarning: { color: "#747580", fontSize: 13, marginBottom: 8 },
  settingsPhrase: { fontSize: 15, lineHeight: 22, color: "#25262d" },
  settingsEmpty: { color: "#747580", fontSize: 14 },
  historyParent: { color: "#747580", fontSize: 12, marginLeft: 28, marginBottom: 6 },
  historyItem: { flexDirection: "row", alignItems: "flex-start", gap: 10, paddingVertical: 6 },
  historyChild: { marginLeft: 18 },
  historyCopy: { flex: 1 },
  historyDeleted: { color: "#747580" },
  historyMeta: { color: "#747580", fontSize: 12, marginTop: 2 },
  historyAction: { borderWidth: 1, borderColor: "#595ec7", borderRadius: 8, paddingHorizontal: 10, paddingVertical: 7 },
  historyActionText: { color: "#494da8", fontSize: 13, fontWeight: "600" },
  recoveryCards: { gap: 10 },
  recoveryPhraseCard: { backgroundColor: "white", borderRadius: 10, borderWidth: 1, borderColor: "#d5d6de", padding: 12 },
  recoveryQrCard: { alignSelf: "flex-start", alignItems: "center", gap: 8, backgroundColor: "white", borderRadius: 10, borderWidth: 1, borderColor: "#d5d6de", padding: 10 },
  recoveryCardHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 6 },
  recoveryCardLabel: { color: "#747580", fontSize: 11, fontWeight: "700", letterSpacing: 0.6, textTransform: "uppercase" },
  recoveryCopyButton: { width: 32, height: 32, borderRadius: 7, alignItems: "center", justifyContent: "center", backgroundColor: "#f4f2ed" },
  recoveryCopyIcon: { color: "#494da8", fontSize: 17, fontWeight: "600" },
  legacyPreview: { backgroundColor: "white", borderRadius: 10, borderWidth: 1, borderColor: "#d5d6de", padding: 10, marginBottom: 8 },
  editModalBackdrop: { flex: 1, justifyContent: "center", padding: 24, backgroundColor: "rgba(24, 25, 32, 0.35)" },
  editModalCard: { backgroundColor: "white", borderRadius: 12, padding: 16 },
  editModalTitle: { color: "#25262d", fontSize: 18, fontWeight: "600", marginBottom: 8 },
  editModalActions: { flexDirection: "row", gap: 8 },
  taskPendingDelete: { opacity: 0.55 },
  checkboxPending: { opacity: 0.45 },
  deleteProgressTrack: { height: 3, backgroundColor: "#d5d6de", borderRadius: 2, marginTop: 6, overflow: "hidden" },
  deleteProgressFill: { height: 3, backgroundColor: "#a52a2a" },
});
